#!/bin/bash

# n8n Docker Issues Auto-Fix Script
# Generated by Claude API

echo "n8n Auto-Fix Script"
echo "==================="

# Function to check if the n8n container is running
check_container_status() {
    if docker inspect -f '{{.State.Running}}' n8n > /dev/null 2>&1; then
        echo "✓ n8n container is running"
        return 0
    else
        echo "✗ n8n container is not running"
        return 1
    fi
}

# Function to restart n8n container
restart_container() {
    echo "Restarting n8n container..."
    cd /mnt/c/n8n
    docker-compose down
    docker-compose up -d
    
    # Wait for container to start
    sleep 10
    if check_container_status; then
        echo "✓ Container restarted successfully"
    else
        echo "✗ Failed to restart container"
    fi
}

# Function to check port 5678
check_port() {
    if netstat -tuln | grep -q ":5678 "; then
        echo "✓ Port 5678 is in use"
        netstat -tuln | grep ":5678"
    else
        echo "✗ Port 5678 is not in use"
    fi
}

# Function to fix volume permissions
fix_permissions() {
    echo "Fixing volume permissions..."
    sudo chown -R 1000:1000 /mnt/c/n8n/data
    sudo chmod -R 755 /mnt/c/n8n/data
    echo "✓ Permissions fixed"
}

# Main execution
echo "1. Checking container status..."
check_container_status

echo "2. Checking port..."
check_port

echo "3. Fixing permissions..."
fix_permissions

echo "4. Restarting container..."
restart_container

echo "Auto-fix complete!"
echo "Access n8n at: http://localhost:5678"