name: Claude API Integration

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:  # 手動実行用

jobs:
  claude-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # タイムアウト設定
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        npm install axios
        
    - name: Call Claude API
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        node - <<'EOF'
        const axios = require('axios');
        
        async function callClaude() {
          try {
            const response = await axios.post(
              'https://api.anthropic.com/v1/messages',
              {
                model: 'claude-3-5-sonnet-20241022',
                max_tokens: 1024,
                messages: [{
                  role: 'user',
                  content: `GitHub Issue: ${process.env.ISSUE_TITLE || 'Test'}\n\nGenerate implementation plan.`
                }]
              },
              {
                headers: {
                  'x-api-key': process.env.ANTHROPIC_API_KEY,
                  'anthropic-version': '2023-06-01',
                  'content-type': 'application/json'
                },
                timeout: 30000  // 30秒タイムアウト
              }
            );
            
            console.log('Claude Response:', response.data.content[0].text);
          } catch (error) {
            console.error('Error:', error.message);
            if (error.response) {
              console.error('API Error:', error.response.data);
            }
            process.exit(1);
          }
        }
        
        callClaude();
        EOF
        
    - name: Comment on Issue
      if: github.event_name == 'issues'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Claude API integration test completed!'
          })