name: セキュリティスキャン

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # 毎週月曜日の午前9時（JST）に実行
    - cron: '0 0 * * 1'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: チェックアウト
      uses: actions/checkout@v4

    - name: Node.js セットアップ
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: NPM監査実行
      run: npm audit
      continue-on-error: true

    - name: 依存関係インストール
      run: npm ci

    - name: Snyk脆弱性スキャン
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: CodeQLセットアップ
      uses: github/codeql-action/init@v3
      with:
        languages: javascript, typescript

    - name: CodeQL分析実行
      uses: github/codeql-action/analyze@v3