name: Test Claude API

on:
  workflow_dispatch:
    inputs:
      test_message:
        description: 'Test message for Claude'
        required: true
        default: 'Hello Claude, please respond with a simple greeting.'

jobs:
  test-api:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Claude API
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        curl -X POST https://api.anthropic.com/v1/messages \
          -H "x-api-key: $ANTHROPIC_API_KEY" \
          -H "anthropic-version: 2023-06-01" \
          -H "content-type: application/json" \
          -d '{
            "model": "claude-3-5-sonnet-20241022",
            "max_tokens": 256,
            "messages": [{
              "role": "user",
              "content": "${{ github.event.inputs.test_message }}"
            }]
          }'